### ISSUE TITLE
[Refactoring] MemberType 리팩토링

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#154]
토큰을 쿠키로 이관하면서 응답에는 `member`만 남은 상태임
굳이.. data.member.xx로 갈 필요 없이 member로 묶는 부분을 지울 예정

```ts
export interface MemberType {
  member: {
    id?: number;
    name?: string;
    group: GroupType | null;
    guest?: boolean;
    type?: AuthType;
  };
}
```

## 주의할 점
프론트에서 `member` 유무 상관 없이 모두 처리할 수 있게 먼저 대응 ㄱㄱ
서버 수정이 완료되면 `member` 없는 타입만 남길 것

### 왜 지금은 data.member.xx로 접근해야 하는지?
```ts
  login: async ({ member }: MemberType): Promise<MemberType> => {
    const { data } = await api.post(authApi.endPoint.login, {
      name: member.name,
    });
    return { member: data.member }; // 여기서 한번 묶어주니까
  },
```

### 둘 다 대응하려면 어떻게 해야 할지?
`MemberType`을 `member` 없는 방향으로 수정해놓고, 서버에서 `member` 있는 데이터가 왔을 때 스프레드 연산자로 찢어서 반환하기

###  TODO
- [x] userState atom 타입 수정
- [x] 컴포넌트에서는 data.xx로 바로 접근하게 수정해두기
- [x] api 응답에서는 member 유무에 따라 적절한 값 반환 

  | `member`가 있다 (변경 전) | `member`가 없다 (변경 후) |
  |:---:|:---:|
  | data.member를 반환 | data를 반환 |
