### ISSUE TITLE
[Feature] 회원탈퇴 페이지 구현

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#279]
## to-do
- [x] setting 페이지에 회원 탈퇴 메뉴 만들기
- [x] 회원 탈퇴 페이지로 이동하기
- [x] 탈퇴하면 어떻게 되는지 -> 랭킹 복원 불가 등등,, 고런 내용
- [x] 탈퇴 API 연결
- [x] 탈퇴 후 처리 (토스트 띄우기 + 앱에 로그아웃 이벤트 / 로컬 데이터 삭제)

![image](https://github.com/user-attachments/assets/256d74b7-901f-4647-8e3e-a2cf474e57f2)

**Comment by nijuy** [comment]
@0chil @Hwanvely 

회원 탈퇴와 관련해서 사용자가 알아야 할 내용 알려주시면 반영하겠습니다!!

- 탈퇴 후 같은 소셜 계정으로 재가입이 가능한지
- 탈퇴와 동시에 모든 데이터 (랭킹, 게임 전적, ...) 는 삭제되는지,
  혹은 탈퇴 후에도 보존하는 데이터가 있는지 등등.. 

요런 것들이 궁금합니다

**Comment by 0chil** [comment]
@nijuy 
1. 재가입 가능하게 해야한다고 생각합니다. (그렇게 구현 예정)
2. 기술적으로는 둘 다 가능한 상황이라 랭킹, 전적 및 경험치를 제거해야 할지 유지해둬야할지 고민이 되네요.
어떻게해야 사용자가 불편한 일이 없을까요?
개인적으로는 실수로 탈퇴하는 경우를 막기 위해 30일정도 후 삭제하는 방식이 좋을 것 같긴 한데,
어떤 방식이 좋다고 생각하시는지 의견 부탁드리겠습니다.

**Comment by 0chil** [comment]
@nijuy 참고로 API endpoint는 `DELETE /members/me`가 된다고 생각하고 진행해주시면 좋을 것 같습니다

**Comment by nijuy** [comment]
@0chil 

1. 굿굿입니다 굳이 막을 이유가 없어보이긴 하네요!
2. 으으음 어렵 다
  
    - 설정 페이지에서 `로그아웃`과 `회원탈퇴`의 메뉴가 구분되어 있다
    - `회원 탈퇴`는 별도 페이지에서 안내 사항을 읽고 동의해야 처리가 완료된다 (누르면 바로 처리되는 `로그아웃`과 달리)
  
    ![image](https://github.com/user-attachments/assets/6538374a-2def-4e04-b3d3-799bb66edd34)
  
    (사진은 대략적인 UI입니다! 모달로 처리할까 했는데, 중요한 내용이 담긴 거라 페이지가 낫겠더라고용)

    위 내용을 생각했을 때, 저는 즉각 삭제도 괜찮다고 생각합니다! 

3. 엔드포인트 확인했습니다!! ^ㅅ^

**Comment by 0chil** [comment]
그럼 일단 즉시 삭제하는 방향으로 가볼게요! 완성되면 말씀드리겠습니다
