### ISSUE TITLE
[TroubleShooting] 비로그인 상태에서 게임 시작하면 가만히 멈춰있는 문제

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#283]
## AS-IS

비로그인 상태에서 게임을 시도하면 `gameStart` api 콜에서 에러 발생

그냥 덩그러니...... 영원히 2분인채로........ 남아있음

![game](https://github.com/user-attachments/assets/8c10fa36-db66-4ccb-90df-fea76940425e)

## TO-BE

비로그인 상태에서 게임을 시도하면 **알아서 게스트 로그인** ➡️ `gameStart` api 

### TO-DO
일단 떠오르는 대로 써봄 

#### 방법 1
- [ ] `기본 모드` 누르면
- [ ] 로그인 여부 확인
- [ ] 비로그인 상태라면 게스트 로그인

#### 방법 2
근데 gameStart 하나만을 위해 인터셉터를 만든다는게 좀 뭔가... 용도에 안 맞는 쓰임 같기도 함
그리고 게스트 로그인 한 걸 유저한테 토스트로 알려줘야 하는데 useToast 쓰려면 1로 가는게

- [ ] game api에 response interceptor를 만들어서
- [ ] code & 로컬 스토리지에 있는 유저 정보 확인하고
- [ ] 유저 정보 없으면 interceptor 내에서 게스트 로그인 시도
- [ ] 게스트 로그인 끝나면 원래 요청 (게임 시작) 다시 보내기

| 게임 시작했을 때 에러 케이스 | 코드 |
|:---:|:---:|
|로그인 했는데 쿠키에 토큰이 없다 | code A |
|로그인 했는데 쿠키에 이상한 토큰이 들어있다 | code B |
|로그인 안 해서 쿠키에 토큰이 없다 | code B -> 이때만 게스트 로그인 시도해야 함|

**Comment by nijuy** [comment]
동의합니다 찬성합니다...........🧹
