### ISSUE TITLE
[Feature] 랭킹 페이지 상단 공지사항 추가

### ISSUE THREAD

**Issue by nijuy** [snack-game/front#310]
## 목적
현재는 `시즌 n` 형식으로 되어있어서 정확한 시작/종료를 파악하기 어려움

## UI
<img src="https://github.com/user-attachments/assets/7471f38f-603d-4e7b-a3da-a2f9e39425bf" width="400">

## TODO

- [x] 공지 페이지 추가
- [x] 랭킹 페이지에 공지 컴포넌트 추가
- [x] 랭킹 페이지의 공지를 클릭하면 해당 공지의 전체 내용을 볼 수 있게 이동

## 🤔
공지 페이지 내에서 다시 세부 공지 페이지로 나누기엔 굳이? 싶음 (하나의 내용이 길지 않을 거 같아서)
클릭보다는 스크롤만 하면 볼 수 있게 하는 게 더 편하다는 말을 어디서  줏어들은 적이 있는데 UX 측면으로 좀 더 찾아보기
